(function(r,p,u,t,l){r[p]=r[p]||{};for(r[p].q=r[p].q||[];l<t.length;)u(t[l++],r[p])})(window,"extole",function(r,p){p[r]=p[r]||function(){p.q.push([r,arguments])}},["log"],0);
extole.define||function(){function r(c){c=l(c);return e[c]}function p(c,k){extole.log("error","[REQUIRE] "+c,k)}function u(c,k){if(c.length)for(var m=0;m<c.length;m++)k(c[m],m);else for(m in c)Object.prototype.hasOwnProperty.call(c,m)&&k(c[m],m)}function t(c,k){var m=[];u(c,function(w,x){m[x]=k(w,x)});return m}function l(c){return"string"!==typeof c?c:/origin-\d/.test(c)?c.substring(c.indexOf("type=")).replace(/version=\d+:/,""):c}function v(c){var k=c.split("/").slice(-1)[0],m=k.length;u(k.toLowerCase(),
function(w){m+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(w)});return c.replace("origin","origin-"+m%8)}function h(c){var k=/^extole-creatives:/.test(c),m=/^extole-media:/.test(c),w=/^core-root:\/\//.test(c),x=/^extole-assets:/.test(c),B=/origin\./.test(c),A=/^http:/.test(c),G=/^https:/.test(c);return k?(c=c.slice(17),h("extole-assets:/core-modules/"+c)):x?(c=c.slice(14),h("extole-media:/assets/"+c)):m?(c=c.slice(13),c=extole.CORE_ROOT+c,h(c)):w?(c=c.slice(12),c=extole.CORE_ROOT+c,h(c)):B?
(c=v(c),c+="?site="+window.location.hostname,h(c)):A?(c=c.slice(5),h(c)):G?(c=c.slice(6),h(c)):c}function g(){}function d(){var c="undefined"!==typeof window.opera&&"[object Opera]"===window.opera.toString(),k=document.createElement("script");this.useInteractive=k.attachEvent&&!(k.attachEvent.toString&&0>k.attachEvent.toString().indexOf("[native code"))&&!c}function b(){u(e,function(c){c._fetched?c._defined||c.define():c.fetch()})}function f(c,k,m,w,x){if("$config"!=c){var B=r(c),A=B||new g;B||(B=
l(c),e[B]=A);c&&k&&(A._fetched=!0);A.start=A.start||(new Date).getTime();A.url=A.url||c;A.dependencies=A.dependencies||k;A.config=A.config||w;A.definedCallback=A.definedCallback||m;A.isRequire=A.isRequire||x}}function a(c,k,m,w){c instanceof Array&&(w=m,m=k,k=c,c=void 0);n.addDefine({url:c,dependencies:k,definedCallback:m,config:w})}var e={};g.prototype={getUnresolvedDependencies:function(){var c=[];u(this.dependencies,function(k){"$config"!=k&&(k=r(k),(!k||k&&!k._defined)&&c.push(k))});return c},
getDependencies:function(){var c=this,k=[];u(c.dependencies,function(m){m="$config"==m?c.config||null:r(m).definition||null;k.push(m)});return k},define:function(){function c(x){k.definedCallback=void 0;k.definition=x;k.end=(new Date).getTime();k.timeToDefine=k.end-k.start;k._defining=!1;k._defined=!0;setTimeout(b,1)}var k=this;k.defineStartTime=k.defineStartTime||(new Date).getTime();if(!k._defining&&!k._defined&&k.dependencies)if(k._defining=!0,0<k.getUnresolvedDependencies().length)k._defining=
!1;else{var m=k.getDependencies(),w={isAsync:!1,async:function(){k.isAsync=!0;w.isAsync=k.isAsync;return function(x){c(x)}}};(function(){if(k.definedCallback){var x=k.definedCallback;x=x&&x.apply(w,m);w.isAsync||c(x)}else c(!0)})()}},fetch:function(){var c=this;c._fetching||c._fetched||(c.url?(c._fetching=!0,c.startFetchTime=(new Date).getTime(),n.loadModule(c.url,function(){c._fetching=!1;c.endFetchTime=(new Date).getTime();c.timeToFetch=c.endFetchTime-c.startFetchTime;c._fetched=!0;c.define()})):
p("Tried to fetch a module without a url - dependencies: "+c.dependencies+" definedCallback: "+(c.definedCallback?"exists":"null")+" config: "+c.config))}};d.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(n.interactiveScript&&"interactive"==n.interactiveScript.readyState)return n.interactiveScript;for(var c=document.getElementsByTagName("head")[0].getElementsByTagName("script"),k,m=c.length-1;0<=m;m--){var w=this.getScriptDataUrl(c[m]);
c[m]&&"interactive"==c[m].readyState&&w&&(k=c[m])}return k},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(c){return c.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(c,k){c.setAttribute(this.scriptUrlAttributeName,k)},attachOnLoad:function(c,k){function m(B){var A=c.readyState;if(w&&"interactive"==A)this.interactiveScript=c;else if("load"===B.type||x.test(A))w?c.detachEvent("onreadystatechange",m):c.removeEventListener("load",m,!1),k(B)}k=k||function(){};
var w=this.useInteractive,x="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/;w?c.attachEvent("onreadystatechange",m):c.addEventListener("load",m,!1)},defineTimeout:null,addDefine:function(c){if(c.url)c.url=h(c.url);else{var k=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&k&&(k=this.getScriptDataUrl(k),c.url=k,this.interactiveScript=null)}c.dependencies=t(c.dependencies,h);this.useInteractive&&!c.url&&p("defines should not be missing a url in ie.");
this.defineQueue.push(c);this.defineTimeout&&clearTimeout(this.defineTimeout);var m=this;this.defineTimeout=setTimeout(function(){m.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var c=[],k;k=this.defineQueue.shift();){var m=[];u(k.dependencies,function(w){w&&m.push(w)});k.url&&r(k.url);k.url||c.push("deps "+k.dependencies);u(m,function(w){f(w)});f(k.url,m,k.definedCallback,k.config,k.isRequire)}this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(b,
1)},loadModule:function(c,k){var m=document.createElement("script");m.async=!0;m.crossOrigin="anonymous";this.setScriptDataUrl(m,c);var w=this;this.attachOnLoad(m,function(){clearTimeout(x);if(!w.useInteractive){for(var A,G=w.defineQueue.length-1;0<=G;G--)w.defineQueue[G].url||(A&&p("Multiple anonymous modules loaded in one script - "+c),A=w.defineQueue[G]);A&&(A.url=c)}w.intakeDefines();k&&k(null)});m.src=c;var x=setTimeout(function(){extole.log("warn","[REQUIRE] Module did not load within 2000ms: ",
{moduleUrl:c})},2E3);this.currentlyAddingScript=m;var B=document.getElementsByTagName("head")[0]||document.head;B?B.appendChild(m):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+c,void 0);this.currentlyAddingScript=void 0}};var n=new d;a.getModule=function(c){return r(c)};var q=0;extole.define=a;extole.require=function(c,k){var m=n,w=m.addDefine;q++;w.call(m,{url:"anonymous_"+q,dependencies:c,definedCallback:k,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:h}});
setTimeout(function(){var c=!1,k=[];u(e,function(m){m._defined||(c=!0);k.push({defineStartTime:m.defineStartTime,dependencies:m.dependencies,end:m.end,start:m.start,isRequire:m.isRequire,timeToDefine:m.timeToDefine,url:m.url,_defined:m._defined,_defining:m._defining,_fetched:m._fetched})});c&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error","After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(k)+"###")},7E3)}();
(function(){try{(function(r,p,u,t,l){r[p]=r[p]||{};for(r[p].q=r[p].q||[];l<t.length;)u(t[l++],r[p])})(window,"extole",function(r,p){p[r]=p[r]||function(){p.q.push([r,arguments])}},["createZone"],0),(new Function('extole.isFindElementBeforeZoneRequest = true;\nextole.LOG_EXCLUDE_REGEX = /__reactInternalInstance/;\n\nextole.createZonePrehandler = function (zoneDefinition, zoneData) {\n    "use strict";\n    if (zoneDefinition.name === "global_header") {\n        if (!zoneData.partner_user_id) {\n            return false;\n        }\n\n        var stringifiedParams = JSON.stringify([zoneDefinition, zoneData]);\n        \n        if (extole.globalHeaderParams === stringifiedParams) {\n            return false;\n        }\n\n        extole.globalHeaderParams = stringifiedParams;\n        return true;\n    }\n    \n    return !/Chrome-Lighthouse/.test(navigator.userAgent);\n};'))()}catch(r){extole.log("error",
"Error executing extended core javascript. Message: "+r.message+" Stack: "+r.stack)}})();
extole.define("extole-uri-parser",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/uri.js"],function(r,p){var u=/^extole_(?!zone)/,t=/^extole_zone_/;return new function(){function l(g){var d={};g=g||h;r.each(g,function(b,f){u.test(f)&&(f=f.replace(u,""),d[f]=b)});return d}function v(){var g,d,b={};this.withName=function(f){g=f;return this};this.withElementId=function(f){d=
f;return this};this.withData=function(f,a){b[f]=a;return this};this.build=function(){var f={};g&&(f.name=g);d&&(f.elementId=d);b&&(f.data=b);return f}}var h=p.deserialize(location.search);this.parseUriZoneDefinition=function(g){var d=new v,b;g=g||h;var f=l(g);r.each(f,function(a,e){d.withData(e,a)});r.each(g,function(a,e){t.test(e)&&(e=e.replace(t,""),"name"===e?(b=!0,d.withName(a)):"element_id"===e?d.withElementId(a):d.withData(e,a))});return b?d.build():null};this.parseGlobalZoneParameters=l}});
(function(r,p,u,t,l){r[p]=r[p]||{};for(r[p].q=r[p].q||[];l<t.length;)u(t[l++],r[p])})(window,"extole",function(r,p){p[r]=p[r]||function(){p.q.push([r,arguments])}},["createZone","log"],0);
(function(){var r=[{name:"Shutterstock Branded Domain",programDomain:"share.shutterstock.com",sitePatterns:"share.shutterstock.com shutterstock.com *.shutterstock.com shuttercloud.org *.shuttercloud.org qa.shutterstock.com *.qa.shutterstock.com".split(" "),siteRegexPatterns:"share\\.shutterstock\\.com\\.?$ shutterstock\\.com\\.?$ .*\\.shutterstock\\.com\\.?$ shuttercloud\\.org\\.?$ .*\\.shuttercloud\\.org\\.?$ qa\\.shutterstock\\.com\\.?$ .*\\.qa\\.shutterstock\\.com\\.?$".split(" ")}];extole.CORE_ROOT=
"https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175";extole.CORE_CONFIG={backendTargetingEnabled:!0,isCookieConsentEnabled:!1,isJsCreativeRespondsWithHtmlEnabled:!1,isGlobalZoneParametersEnabled:!1,isAccessTokenIncludedInResponseEnabled:!0,cookieConsentPolicy:"COOKIE_CONSENT_OR_SESSION_COOKIE",cookieConsentEnabled:!1};extole.CLIENT_ID="1528233037";extole.BUILD_DATE="1700633309485";extole.VERSION="6.0";extole.IS_DEBUG_ENABLED=extole.debug||/[?&]extole_debug=true(&|$)/.test(location.search);
extole.PROGRAM=function(){function p(d,b){d=Error.call(this,d);this.name="ExtoleError";this.message=d.message;this.stack=d.stack;this.code=b}function u(d,b){if(d.length)for(var f=0;f<d.length;f++)b(d[f],f);else for(f in d)Object.prototype.hasOwnProperty.call(d,f)&&b(d[f],f)}function t(d,b){var f=[];u(d,function(a){(a=b(a))&&(f[f.length]=a)});return f}function l(d,b){b=b||[];var f=!1;u(b,function(a){(new RegExp(a)).test(d)&&(f=!0)});return f}function v(){extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/uri.js",
"https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ajax.js"],function(d,b){var f=extole.CORE_ROOT;d=f.replace(/(https?:\/\/[a-z-\.]+)(\/.*)/,"$1")+"/_extole_core.gif"+d.serialize({core_root:f,referer:window.location.hostname});b({url:d})})}p.prototype=Error();p.prototype.constructor=p;var h=function(d){var b=window.location.hostname;return t(d,function(f){if(l(b,f.siteRegexPatterns))return f})}(r),g=h[0];if(!g)throw v(),new p("No program domain is configured for hostname: "+
window.location.hostname+" unable to use Extole API","site_configuration_error");1<h.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+" programs: "+JSON.stringify(h));return g}();extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/uri.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js","create-zone-executor"],function(p,u,t){function l(){function d(f){var a=f[0];
"function"===typeof b[a]?(b[a].apply(null,f[1]),extole.q.history.push({name:f[0],args:f[1],timestamp:Date.now(),stack:Error().stack})):u.warn("Unable to execute method: "+a+", it is not implemented.")}var b={log:function(){var f=Array.prototype.slice.call(arguments),a=f[0];"function"===typeof u[a]&&u[a].apply(null,f.slice(1))},createZone:t.initiateExecution};for(extole.q.history=[];extole.q.length;)d(extole.q.shift());extole.q.push=d}function v(){extole.require(["extole-uri-parser"],function(d){var b=
p.deserialize(location.search);(d=d.parseUriZoneDefinition(b))&&extole.createZone(d)})}function h(){if("function"===typeof window.onerror)var d=window.onerror;window.onerror=function(b,f,a,e,n){if(d)try{d(b,f,a,e,n)}catch(k){}f=f||window.location.href||"no_source_or_location.href";n=n&&n.stack?n.stack:"no_error.stack";var q=[],c=JSON.stringify({MESSAGE:b,SOURCE:f,LINE_NUMBER:a,COLUMN_NUMBER:e,STACK_TRACE:n},function(k,m){if(null!==m&&"object"===typeof m){if(0<=q.indexOf(m))return;q.push(m)}return m});
a=extole.PROGRAM.programDomain.split(".").join("\\.");a=new RegExp("^(http|https):\\/\\/("+a+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");((n+b).match(/extole/i)||a.test(f))&&extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js"],function(k){k.error("Unhandled exception",JSON.parse(c))})}}function g(){extole._bootstrapped=!0;h();l();v()}extole.bootstrap=g;extole._bootstrapped||g();if("undefined"!==typeof window.extoleAsyncInit)try{window.extoleAsyncInit()}catch(d){extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js"],
function(b){b.error("Error executing extended core javascript. Message : "+d.message+" Stack: "+d.stack)})}})})();
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ExtoleError.js",[],function(){function r(u,t,l,v){u=Error.call(this,u);this.name="ExtoleError";this.message=u.message||"no_message";this.stack=Error().stack;this.code=t||"extole_error";this.data=l||{};this.logLevel=0<=p.indexOf(v)?v:"error"}var p=["debug","info","warn","error"];r.prototype=Error();r.prototype.constructor=r;r.prototype.toString=function(){return this.name+" ["+this.logLevel+"]: message: "+
this.message+"; code: "+this.code+"; data: "+JSON.stringify(this.data,null,4)+"; stack trace: "+this.stack+";"};return r});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ExtoleError.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/type.js"],function(r,p){function u(l,v){var h;if(l.length===Number(l.length))for(h=0;h<l.length;h++){var g=v(l[h],h);if(!1===g)return!1}else for(h in l)if(Object.prototype.hasOwnProperty.call(l,h)&&(g=v(l[h],
h),!1===g))return!1}function t(l){if(!l||"object"!==typeof l&&!p.isPlainFunction(l))l={};for(var v=1;v<arguments.length;v++)if(p.isPlainObject(arguments[v]))for(var h in arguments[v]){var g=arguments[v][h];g!==l&&void 0!==g&&(p.isPlainObject(g)&&p.isPlainObject(l[h])?g=t(l[h],g):p.isArray(g)&&p.isArray(l[h])&&l[h].concat&&(g=l[h].concat(g)),l[h]=g)}return l}u.BREAK=!1;return{each:u,map:function(l,v){function h(b,f){d=[];u(b,function(a,e){d.push(f(a,e))})}function g(b,f){d={};u(b,function(a,e){d[e]=
f(a,e)})}var d;if(p.isArray(l))h(l,v);else if(p.isPlainObject(l))g(l,v);else throw new r(l+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return d},filter:function(l,v){function h(b,f){d=[];u(b,function(a,e){f(a,e)&&d.push(a)})}function g(b,f){d={};u(b,function(a,e){f(a,e)&&(d[e]=a)})}var d;if(p.isArray(l))h(l,v);else if(p.isPlainObject(l))g(l,v);else throw new r(l+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return d},merge:t,clone:function(l){return JSON.parse(JSON.stringify(l))},
flatten:function(l){function v(g,d){if(p.isPlainObject(g))u(g,function(f,a){var e=d.slice();e.push(a);v(f,e)});else{var b=d.join(".");h[b]=g}}if(!p.isPlainObject(l))return l;var h={};v(l,[]);return h},find:function(l,v){var h;u(l,function(g,d){if(v(g,d))return h=g,u.BREAK});return h},reverse:function(l){var v=[];if(!l||l.length!==Number(l.length))return l;for(var h=l.length-1;0<=h;h--)v.push(l[h]);return v},nashornToJs:function(l){if(p.isPlainJs(l)||!l)return l;if(p.isJavaMap(l)){var v={};for(var h in l)v[h]=
l[h]}else if(p.isNumber(l.length))v=[],u(l,function(g,d){v[d]=g});else return l;return v},intersection:function(l,v){var h=[];u(l,function(g){0>v.indexOf(g)||0<=h.indexOf(g)||h.push(g)});return h},difference:function(l,v){var h=[];u(l,function(g){0<=v.indexOf(g)||0<=h.indexOf(g)||h.push(g)});return h}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js"],function(r){function p(h){try{return decodeURIComponent(h.replace(t," "))}catch(g){return r.info("** cookie.decode ** Cookie error for: "+h,{error:g,message:g.message,stack:g.stack,cookiePart:h}),""}}function u(h){h=p(h);return 0===h.indexOf('"')?h.slice(1,-1).replace(l,'"').replace(v,"\\"):h}var t=
/\+/g,l=/\\"/g,v=/\\\\/g;return function(h,g,d){if(void 0!==g){d=d||{};var b=document;h=encodeURIComponent(h);g=encodeURIComponent(g);if(d.expires){var f=d.expires;if(!f||!f.toUTCString){var a=new Date;a.setDate(a.getDate()+("number"===typeof f?f:0));f=a}f="; expires="+f.toUTCString()}else f="";return b.cookie=[h,"=",g,f,d.path?"; path="+d.path:"",d.domain?"; domain="+d.domain:"",d.samesite?"; samesite="+d.samesite:"","; secure"].join("")}a:{d=document.cookie?document.cookie.split("; "):[];b=h?null:
{};g=0;for(f=d.length;g<f;g++){a=d[g].split("=");var e=p(a[0]);if(!h)b[e]=u(a[1]);else if(h===e){h=u(a[1]);break a}}h=b}return h}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/device-type.js",[],function(){function r(t){return p.test(t)}var p=RegExp("Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|Dolphin|Fennec|(hpw|web)OS|Zune|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Silk-Accelerated|Skyfire|NetFront","i"),u=/WebView|\swv|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(Version\/\d+\.\d+\s)|Linux; U; Android/i;return{isMobile:r,isDesktop:function(t){return!r(t)},isWebview:function(t){return u.test(t)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/dom.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js"],function(r){function p(b,f){return(f||document).querySelectorAll(b)}function u(b,f){return p(b,f)[0]}function t(b,f){function a(){clearTimeout(n);f(e);v.removeListener(e,"load",a)}f=f||function(){};if(d[b]||!b)return f(d[b]),d[b]||null;d[b]=document.createElement("link");var e=d[b];h.setAttribute(e,
"rel","stylesheet");h.setAttribute(e,"href",b);g.append(u("head"),e);v.addListener(e,"load",a);var n=setTimeout(function(){r.warn("Load timeout reached for stylesheet: ",{url:b});a()},5E3);return e}var l={each:function(b,f){var a;if(b.length===Number(b.length))for(a=0;a<b.length;a++){var e=f(b[a],a);if(!1===e)return!1}else for(a in b)if(Object.prototype.hasOwnProperty.call(b,a)&&(e=f(b[a],a),!1===e))return!1},extend:function(){var b,f,a=arguments[0]||{},e=1,n=arguments.length,q=!1,c=this.extend;"boolean"===
typeof a&&(q=a,a=arguments[1]||{},e=2);for("object"===typeof a||this.isFunction(a)||(a={});e<n;e++){var k=arguments[e];if(null!==k)for(b in k){var m=a[b];var w=k[b];a!==w&&(q&&w&&(this.isPlainObject(w)||(f=this.isArray(w)))?(f?(f=!1,m=m&&this.isArray(m)?m:[]):m=m&&this.isPlainObject(m)?m:{},a[b]=c(q,m,w)):void 0!==w&&(a[b]=w))}}return a},isFunction:function(b){return b&&"function"===typeof b&&b.call&&b.apply},isPlainObject:function(b){if("[object Object]"!==String(b)||b.nodeType||b.window&&b.window==
b)return!1;try{if(b.constructor&&!Object.prototype.hasOwnProperty.call(b.constructor.prototype,"isPrototypeOf"))return!1}catch(f){return!1}return!0},isArray:function(b){return b instanceof Array}};l.each.BREAK=!1;var v=function(){function b(q,c,k){for(var m=[],w=0;w<n.length;w++){var x=n[w];x.element==q&&x.eventType==c&&x.listener==k&&m.push({index:w,eventListener:x})}return m}function f(q){for(var c=[],k=0;k<n.length;k++){var m=n[k];m.element===q&&c.push(m)}return c}function a(q){this.originalEvent=
q;this.type=q.type;this.keyCode=q.keyCode;this.target=q.srcElement?q.srcElement:q.target}function e(q,c,k){k=b(q,c,k);0>=k.length?r.info("events.remove - Couldn't find exiting event listener for type \""+c+'" listener on element '+q):l.each(k,function(m){var w=m.index;m=m.eventListener;q.removeEventListener?q.removeEventListener(c,m.listenerWrapper,!1):q.detachEvent("on"+c,m.listenerWrapper);n.splice(w,1)})}var n=[];a.prototype={preventDefault:function(){var q=this.originalEvent;q.preventDefault?
q.preventDefault():q.returnValue=!1},stopPropagation:function(){var q=this.originalEvent;q.stopPropagation&&q.stopPropagation();q.cancelBubble=!0}};return{addListener:function(q,c,k){function m(x){w&&(x=window.event);return k.call(q,new a(x))}if(0<b(q,c,k).length)r.warn("events.add - Listener already exists for event "+c+" on element "+q);else{var w=!q.addEventListener;n.push({element:q,eventType:c,listener:k,listenerWrapper:m});q.addEventListener?q.addEventListener(c,m,!1):q.attachEvent("on"+c,m)}},
triggerEvent:function(q,c,k){var m=document.createEvent("Event");k=l.extend({},k);var w=!1===!k.bubbles,x=!0===k.cancelable;delete k.bubbles;delete k.cancelable;m.initEvent(c,w,x);l.extend(m,k);q.dispatchEvent(m)},removeListener:e,clearListeners:function(q){q=f(q);l.each(q,function(c){e(c.element,c.eventType,c.listener)})}}}(),h=function(){function b(a){a=a.className;var e={};if(!a)return e;l.each(a.split(" "),function(n){e[n]=1});return e}function f(a){var e="";l.each(a,function(n,q){e+=" "+q});
return e.slice(1)}return{setAttribute:function(a,e,n){a.setAttribute(e,n);a[e]=n},getAttribute:function(a,e){return a.getAttribute(e)},removeAttribute:function(a,e){return a.removeAttribute(e)},addClass:function(a,e){var n=b(a);n[e]||(n[e]=1,a.className=f(n))},removeClass:function(a,e){var n=b(a);delete n[e];a.className=f(n)},getClassNames:function(a){return a.className.split(" ")}}}(),g=function(){function b(a){var e=document.createDocumentFragment(),n=document.createElement("div");n.innerHTML=a;
l.each(n.childNodes,function(q){1==q.nodeType&&e.appendChild(q)});return e}function f(a){var e;l.each(a.childNodes,function(n){if(!e&&1==n.nodeType)return e=n,l.each.BREAK});return e}return{prepend:function(a,e){var n=f(a),q=e;"string"===typeof e&&(q=b(e));n?a.insertBefore(q,n):a.appendChild(q)},append:function(a,e){var n=e;"string"===typeof e&&(n=b(e));a.appendChild(n)}}}(),d={};return{addEventListener:v.addListener,removeEventListener:v.removeListener,triggerEvent:v.triggerEvent,clearEventListeners:v.clearListeners,
getAttribute:h.getAttribute,setAttribute:h.setAttribute,removeAttribute:h.removeAttribute,addClass:h.addClass,removeClass:h.removeClass,getClassNames:h.getClassNames,prepend:g.prepend,append:g.append,query:p,queryFirst:u,isVisible:function(b,f){return!!(u(b,f)||{}).offsetParent},injectStylesheet:t,injectStylesheets:function(b,f){function a(q){--e||f(n)}f=f||function(){};if(0===b.length)f();else{var e=0,n=[];l.each(b,function(q){e++;setTimeout(function(){n.push(t(q,a))},1)})}},scrollIntoViewIfNeeded:function(b,
f){function a(w,x){return{start:w,length:x,end:w+x}}function e(w,x){return!1===f||x.start<w.end&&w.start<x.end?Math.min(w.start,Math.max(x.start,w.end-x.length)):(w.start+w.end-x.length)/2}function n(w,x){return{x:w,y:x,translate:function(B,A){return n(w+B,x+A)}}}function q(w,x){for(;w;)x=x.translate(w.offsetLeft,w.offsetTop),w=w.offsetParent;return x}var c=q(b,n(0,0)),k=n(b.offsetWidth,b.offsetHeight);b=b.parentNode;for(var m;b instanceof HTMLElement;)m=q(b,n(b.clientLeft,b.clientTop)),b.scrollLeft=
e(a(c.x-m.x,k.x),a(b.scrollLeft,b.clientWidth)),b.scrollTop=e(a(c.y-m.y,k.y),a(b.scrollTop,b.clientHeight)),c=c.translate(-b.scrollLeft,-b.scrollTop),b=b.parentNode}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/event-bus.js",[],function(){function r(){function t(h,g,d,b){if(!d)return!0;if("object"===typeof d){for(var f in d)h[g].apply(h,[f,d[f]].concat(b));return!1}if(v.test(d)){d=d.split(v);f=0;for(var a=d.length;f<a;f++)h[g].apply(h,[d[f]].concat(b));return!1}return!0}function l(h,g){var d,b=-1,f=h.length,a=g[0],e=g[1],n=g[2];switch(g.length){case 0:for(;++b<f;)(d=h[b]).callback.call(d.ctx);break;case 1:for(;++b<
f;)(d=h[b]).callback.call(d.ctx,a);break;case 2:for(;++b<f;)(d=h[b]).callback.call(d.ctx,a,e);break;case 3:for(;++b<f;)(d=h[b]).callback.call(d.ctx,a,e,n);break;default:for(;++b<f;)(d=h[b]).callback.apply(d.ctx,g)}}this._events={};var v=/\s+/;this.on=function(h,g,d){if(!t(this,"on",h,[g,d])||!g)return this;this._events||(this._events={});(this._events[h]||(this._events[h]=[])).push({callback:g,context:d,ctx:d||this});return this};this.off=function(h,g,d){var b,f,a;if(!this._events||!t(this,"off",
h,[g,d]))return this;if(!h&&!g&&!d)return this._events=void 0,this;var e=h?[h]:u.keys(this._events);var n=0;for(f=e.length;n<f;n++)if(h=e[n],b=this._events[h]){var q=[];this._events[h]=q;if(g||d){var c=0;for(a=b.length;c<a;c++){var k=b[c];(g&&g!==k.callback&&g!==k.callback._callback||d&&d!==k.context)&&q.push(k)}}q.length||delete this._events[h]}return this};this.once=function(h,g,d){function b(){var a=p.call(arguments);f.off(h,b,d);g.apply(this,a)}var f=this;this.on(h,b,d);return this};this.trigger=
function(h){if(!this._events)return this;var g=p.call(arguments,1);if(!t(this,"trigger",h,g))return this;var d=this._events[h],b=this._events.all;d&&l(d,g);b&&l(b,arguments);return this}}var p=Array.prototype.slice,u={isPlainObject:function(t){if("[object Object]"!==String(t)||t.nodeType||t.window&&t.window==t)return!1;try{if(t.constructor&&!Object.prototype.hasOwnProperty.call(t.constructor.prototype,"isPrototypeOf"))return!1}catch(l){return!1}return!0},keys:function(t){if(!this.isPlainObject(t))return[];
var l=[],v;for(v in t)Object.prototype.hasOwnProperty.call(t,v)&&l.push(v);return l},_idCounter:0,uniqueId:function(t){var l=String(++this._idCounter);return t?t+l:l}};return{create:function(){return new r}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js",[],function(){function r(a,e,n){l||(l=e.getGlobalServices().getJsLoggingService());l[a](n)}function p(a,e,n){var q=String(extole.CORE_ROOT).match(/coreAssetsVersion=(\d+)/);n=n||{};n.pageId=h;n.referer=g;n.coreAssetsVersion=q&&q[1];try{var c=[e||"no message","START_JSON",JSON.stringify(n),"END_JSON"].join(" ")}catch(k){t("Failed to stringify log's json data",{exception:k});return}if(!extole.LOG_EXCLUDE_REGEX||
!c.match(extole.LOG_EXCLUDE_REGEX)){f[c]=++f[c]||1;if(d[a]>=d[extole.LOG_LEVEL_CONSOLE]&&(e=a+" "+c,window.console))if(window.console[a.toLowerCase()])window.console[a.toLowerCase()](e);else window.console.log(e);d[a]>=d[extole.LOG_LEVEL_REMOTE]&&(e=f[c],b[e]&&u(a,c+(1<e?" log count: "+e:"")))}}function u(a,e){extole.require(["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/api.js"],function(n){n.post("/api/v4/debug/logs",{level:a,message:e},null,{headers:{"Content-Type":"application/x-www-form-urlencoded"}})})}
function t(a,e){p("ERROR",a,e)}var l;if("undefined"===typeof window)return{debug:function(a,e){r("debug",a,e)},info:function(a,e){r("info",a,e)},warn:function(a,e){r("warn",a,e)},error:function(a,e){r("error",a,e)},LOGGING_ENDPOINT:"/api/v4/debug/logs"};var v=extole.IS_DEBUG_ENABLED?"DEBUG":"OFF",h=String((new Date).getTime()),g=window.location.href,d={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},b={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||v;extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var f={};return{debug:function(a,e){p("DEBUG",a,e)},info:function(a,e){p("INFO",a,e)},warn:function(a,e){p("WARN",a,e)},error:t,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/Timer.js",[],function(){return function(){var r=this,p;this.start=function(){if(p)throw Error("Timer.start has already been called");p=new Date;return r};this.getElapsedTime=function(){if(!p)throw Error("Timer has not been started");return new Date-p}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/type.js",[],function(){function r(t,l){return function(v){return p(t,v,l)}}function p(t,l,v){v=v||{};t=Object.prototype.toString.call(l)==="[object "+t+"]";l=l&&v.construct?l.constructor===v.construct:!0;return(v.negate?!t:t)&&l}var u=/\[object (Function|Array|String|Boolean|Number|Undefined|Null)\]/;return{isPlainJs:function(t){return this.isPlainObject(t)||u.test(Object.prototype.toString.call(t))},
isJavaMap:function(t){return"undefined"!==typeof Java&&Java.type?t instanceof Java.type("java.util.Map"):!1},isPlainObject:r("Object",{construct:Object}),isPlainFunction:r("Function"),isArray:r("Array"),isString:r("String"),isBoolean:r("Boolean"),isNumber:r("Number"),isUndefined:r("Undefined"),isDefined:r("Undefined",{negate:!0}),isNull:r("Null"),test:p}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/uri.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js"],function(r){function p(g){var d={};(function e(f,a){for(var n in f){var q=f[n],c=(a?a+".":"")+n;"[object Object]"===Object.prototype.toString.call(q)?e(q,c):t(c)&&(d[c]=q)}})(g);return d}function u(g){try{return decodeURIComponent(g)}catch(d){return g}}function t(g){return"__proto__"!==g&&"prototype"!==
g&&"constructor"!==g}function l(g,d,b){d=(d||[]).concat("object"===typeof extole&&extole.PROGRAM?extole.PROGRAM.siteRegexPatterns:[]);b=v(b||location.href);g=v(g);return(/^https?:\/\//.test(g)?r.find(d,function(f){var a=h.exec(g);return(new RegExp(f)).test(a&&a[1])}):1)?g:b}function v(g){return g.replace(RegExp("(j|%4A|%6A)(a|%41|%61)(v|%56|%76)(a|%41|%61)(s|%53|%73)(c|%43|%63)(r|%52|%72)(i|%49|%69)(p|%50|%70)(t|%54|%74)(:|%3A)","gi"),"")}var h=/^https?:\/\/([^/:?#]+)/i;return{serialize:function(g){var d=
"",b;for(b in g)d+="&"+encodeURIComponent(b)+"="+encodeURIComponent(String(g[b]));return d.replace(/^&/,"?")},deserialize:function(g){var d={};if(!g)return d;g=(g.match(/^\?/)?g.slice(1):g).split("&");for(var b=0;b<g.length;b++){var f=g[b].split("="),a=u(f[0]);f=u(f[1]);t(a)&&(d[a]=f)}return d},objectToDotNotation:p,dotNotationToObject:function(g){var d={};g=p(g);for(var b in g){for(var f=d,a=b.split("."),e=a.pop();a.length;){var n=a.shift();t(n)&&(f[n]=f[n]||{},f=f[n])}t(e)&&(f[e]=g[b])}return d},
decodeComponent:u,encodeComponent:function(g){return encodeURIComponent(g)},getSafeRedirectUrl:l,executeSafeRedirect:function(g,d,b){window.location.href=l(g,d,b)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/uri.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/type.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js"],function(r,p,
u,t){function l(d,b){function f(){4!==d.readyState||G||(G=!0,String(d.status||200).match(/^[23]/)?"function"===typeof B?B.call(d,d.responseText,d):t.warn("'complete' callback must be a function."):A.call(d,d.statusText,d.status),n())}function a(H){G||(G=!0,t.error("Error with url "+m+"= "+q.join(","),e(H)),A.call(d,d.statusText,d.status))}function e(H){return{eventType:H&&H.type||null,options:b,readyState:d.readyState,response:d.response,responseText:d.responseText,responseType:d.responseType,responseURL:d.responseURL,
responseXML:d.responseXML,status:d.status,statusText:d.statusText,timeout:d.timeout,responseHeaders:d.getAllResponseHeaders()}}function n(H){0>m.indexOf(t.LOGGING_ENDPOINT)&&t.debug("ajax request complete",e(H))}var q=Array.prototype.slice.call(arguments),c=b.headers||{},k=b.xhrFields||{},m=b.url||"",w=b.data||"",x=(b.type||"get").toUpperCase(),B=b.complete||function(){},A=b.error||function(){};u.isPlainObject(w)&&("GET"===x?(m+=p.serialize(w),w=null):w=JSON.stringify(w));d.open(x,m,!0);r.merge(d,
k);r.each(c,function(H,C){try{d.setRequestHeader(C,H)}catch(I){t.error("AJAX ERROR: Couldn't set request header "+C+" to "+H)}});var G=!1;d.onload=f;d.onreadystatechange=f;d.onerror=a;d.ontimeout=a;d.onabort=n;d.send(w)}function v(d){r.each(d,function(b,f){"content-type"===f.toLowerCase()&&delete d[f]})}function h(d){d=d||{};var b=!1;for(var f=0;f<g.length;f++){try{b=g[f]()}catch(a){continue}break}l(b,d);return b}var g=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},
function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];h.convertToFormUrlEncoded=function(d,b){function f(e){var n={};r.each(e,function(q,c){c=0<=c.indexOf(".")?'"'+c+'"':c;u.isPlainObject(q)&&(q=f(q));n[c]=q});return n}var a=[];v(d);d["content-type"]="application/x-www-form-urlencoded";b=f(b);b=r.flatten(b);r.each(d,function(e,n){"content-type"!==n.toLowerCase()&&(a.push("::headers."+n+"="+e),delete d[n])});r.each(b,function(e,n){u.isUndefined(e)||
a.push(encodeURIComponent(n)+"="+(u.isNull(e)?"":encodeURIComponent(e)))});return a.join("&")};h.convertToMultipartFormData=function(d,b){var f=new FormData;r.each(b,function(a,e){f.append(e,a)});v(d);return f};return h});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},getSiteRegexPatterns:function(){return extole.PROGRAM.siteRegexPatterns},getProtocol:function(){return"https://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/token-store.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/event-bus.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/cookie.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ajax.js".split(" "),
function(r,p,u,t,l,v){function h(){function a(){E[b.MEMORY]=E[b.MEMORY]||new m;E[b.COOKIE]=E[b.COOKIE]||new w;E[b.LOCAL_STORAGE]=E[b.LOCAL_STORAGE]||new x;extole.COOKIES_DISABLED&&(E[b.COOKIE].remove(),delete E[b.COOKIE]);extole.LOCAL_STORAGE_ALWAYS_ENABLED||extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||(E[b.LOCAL_STORAGE].remove(),delete E[b.LOCAL_STORAGE])}function e(y){function z(F,J){D+=1;F?5>D?n(z):(F="Failed to fetch access token after 5 attempts. Last Error: "+
F.message,u.error(F),y(Error(F))):y(null,J)}var D=0;n(z)}function n(y){q("POST","/api/v5/token",null,function(z,D){y(z,D)})}function q(y,z,D,F){function J(K,M){try{var N=JSON.parse(K)}catch(P){M(P);return}M(null,N)}D=D||c();var Q="https://"+extole.PROGRAM.programDomain+z+(D?"?access_token="+D:"");v({url:Q,type:y,headers:{"content-type":"application/json"},complete:function(K){J(K,F)},error:function(K,M){var N=this,P="Api request to "+z+" failed: "+M+" "+K,R={method:y,url:Q,statusText:K||null,http_status_code:M||
null};J(N.responseText,function(O,L){if(O){O="Failed to parse api error response as json";var S="json_parse_error";L=p.merge({response:N.responseText},R)}else O=L.message||P,S=L.code||"failed_api_request",L=p.merge({},L,R);F(new r(O,S,L))})}})}function c(){var y=C===d.YEAR?G():H();return(y=p.find(y,function(z){z=z.get();return!("string"!==typeof z||"undefined"===z||"null"===z||!z.length)}))?y.get():null}function k(y,z){var D=c();if(!y&&D)y=D;else if(!y&&!D)return;var F=D!==y;C=Object.prototype.hasOwnProperty.call(d,
z)&&z||(F||!C?B():C);A(C);p.each(C===d.YEAR?G():H(),function(J){J.set(y,C)});F&&I.trigger("change:access_token");D&&F&&u.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+D+", to: "+y)}function m(){var y={};this.get=function(){return y.extole_access_token};this.set=function(z){y.extole_access_token=z};this.remove=function(){delete y.extole_access_token}}function w(){this.get=function(){return l("extole_access_token")};this.set=function(y,z){l("extole_access_token",y,{expires:f[z.toUpperCase()],
path:"/",samesite:"strict"})};this.remove=function(){l("extole_access_token","",{expires:-1,path:"/"})}}function x(){var y;(function(){var z="test"+(new Date).getTime();try{localStorage.setItem(z,z),localStorage.removeItem(z)}catch(D){y=!1;return}y=!0})();this.get=function(){return y?localStorage.getItem("extole_access_token"):null};this.set=function(z){y&&localStorage.setItem("extole_access_token",z)};this.remove=function(){y&&localStorage.removeItem("extole_access_token")}}function B(){if(extole.CORE_CONFIG.isCookieConsentEnabled)switch(extole.CORE_CONFIG.cookieConsentPolicy){case g.COOKIE_CONSENT_OR_SESSION_COOKIE:return d.SESSION;
case g.COOKIE_CONSENT_OR_NO_COOKIE:return d.NO_COOKIE;default:return d.NO_COOKIE}return d.YEAR}function A(){var y=C===d.YEAR?G():H();p.each(E,function(z){0>y.indexOf(z)&&z.remove()})}function G(){var y=[b.MEMORY];Object.prototype.hasOwnProperty.call(E,b.COOKIE)&&y.push(b.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&y.push(b.LOCAL_STORAGE);return y.map(function(z){return E[z]})}function H(){var y=[b.MEMORY];extole.CORE_CONFIG.cookieConsentPolicy===g.COOKIE_CONSENT_OR_SESSION_COOKIE&&
Object.prototype.hasOwnProperty.call(E,b.COOKIE)&&y.push(b.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&y.push(b.LOCAL_STORAGE);return y.map(function(z){return E[z]})}var C,I=t.create(),E={};a();this.fetch=function(y){y=y||function(){};e(function(z,D){var F=D.access_token;F&&k(F);y(z,D,C)})};this.getTokenDetails=function(y){y=y||function(){};q("GET","/api/v5/token",c(),y)};this.get=c;this.set=k;this.remove=function(){C=B();p.each(E,function(y){y.remove()})};
this.setUnconsented=function(){C=B();k()};this.initializeStores=a;this.events=I}var g={COOKIE_CONSENT_DISABLED:"COOKIE_CONSENT_DISABLED",COOKIE_CONSENT_OR_SESSION_COOKIE:"COOKIE_CONSENT_OR_SESSION_COOKIE",COOKIE_CONSENT_OR_NO_COOKIE:"COOKIE_CONSENT_OR_NO_COOKIE"},d={NO_COOKIE:"NO_COOKIE",SESSION:"SESSION",YEAR:"YEAR"},b={MEMORY:"MEMORY",COOKIE:"COOKIE",LOCAL_STORAGE:"LOCAL_STORAGE"},f={YEAR:365,SESSION:null};extole.tokenStore=extole.tokenStore?extole.tokenStore:new h;return extole.tokenStore});
extole.define("https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/metric-registry.js",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/program.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ajax.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/token-store.js"],function(r,p,u){function t(h,g,d){d={metric_type:h,key:g,value:d};h={"Content-Type":"application/x-www-form-urlencoded",
"X-Extole-App":"javascript_sdk"};u.get()&&(h.Authorization="Bearer+"+u.get(),g=[r.getProtocol(),r.getProgramDomain(),"/api/v4/debug/metrics"].join(""),d=p.convertToFormUrlEncoded(h,d),p({url:g,type:"POST",headers:h,data:d,xhrFields:{withCredentials:!0}}))}function l(h){this.increment=function(g){t("COUNTER",h,g?g:1)}}function v(h){this.update=function(g){t("HISTOGRAM",h,g)}}return{histogram:function(h){return new v(h)},counter:function(h){return new l(h)}}});
extole.define("ZoneBrowserContext",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/uri.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js"],function(r,p){function u(v,h,g){this.getElement=function(){return g};this.getName=function(){return v};this.getData=function(){return h};this.getParameters=function(){return h}}function t(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=function(){return extole.PROGRAM.programDomain};
this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns};this.getSiteRegexPatterns=function(){return extole.PROGRAM.siteRegexPatterns}}function l(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.isCookieConsentEnabled}}return function(v,h,g,d,b){var f=new u(v,h,g),a=new t,e=new l;this.getZone=function(){return f};this.getProgram=function(){return a};this.getCreativeData=function(){var n=r.dotNotationToObject(r.deserialize(location.search)),
q=r.dotNotationToObject(f.getParameters());return p.merge(n.extole_creative,q.creative)};this.getCoreConfig=function(){return e};this.getLocale=function(){return d||null};this.getContainer=function(){return b}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js"],function(r){function p(u,t,l){function v(){if(t())l();else{u();var g=setTimeout;h||(h=10);var d=500<h?500:h*=1.1;g(v,d)}}var h;v()}return function(u,t){var l=(new Date).getTime(),v=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_NOT_FOUND||3E3,h=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_FOUND||2E3,g=!1,d;p(function(){d=document.getElementById(u)},function(){var b=(new Date).getTime()-
l,f=!!d;f&&b>=h?r.debug("EXTOLE_ELEMENT_FOUND_SLOW: Scan duration: "+b+"ms, element id: "+u):!extole.isFindElementBeforeZoneRequest&&!g&&b>=v&&(g=!0,r.debug("EXTOLE_ELEMENT_NOT_YET_FOUND: Scan duration: "+b+"ms, element id: "+u));return f},function(){t(d)})}});extole.define("ensure-element",["find-element-by-id"],function(r){return function(p,u){p.element?u(p.element):p.element_id?r(p.element_id,u):u(document.body.appendChild(document.createElement("div")))}});
extole.define("pending-zone-service","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/dom.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/type.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/token-store.js ZoneBrowserContext ensure-element".split(" "),
function(r,p,u,t,l,v,h){function g(a,e){e=e||function(){};var n=a.name,q=d(a.data);f(n);this.resolve=function(c,k,m,w,x){l.set(k,m);h(a,function(B){a.element=B;r.clearEventListeners(a.element);B=new v(n,q,a.element,w,x);c(B);e(null,B.getZone())})}}function d(a){a=t.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}var b={},f=function(){var a={};return function(e){p.isUndefined(a[e])&&(a[e]=0);a[e]++;if(5===a[e]){e="duplicate_zone_requests : "+e;var n=t.filter(extole.q.history,
function(q){return q.name&&"createZone"===q.name});n=t.map(n,function(q){delete (q.args[0]||{}).element;return q});u.warn(e,n)}}}();return{get:function(a){if(!b[a])throw Error("Pending zone does not exist for id: "+a);return b[a]},create:function(){var a=Math.floor(1E9*Math.random()),e=0;return function(n,q){e++;var c=a+"."+e;b[c]=new g(n,q);return c}}()}});
extole.define("create-zone","extole-uri-parser https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/uri.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/collection.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/dom.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/program.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/token-store.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ajax.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js pending-zone-service".split(" "),function(r,
p,u,t,l,v,h,g,d,b){var f=[];return function(a,e,n){function q(){var C={"Content-Type":"application/x-www-form-urlencoded",Accept:"text/javascript","X-Extole-App":"javascript_sdk"};m=G+"/zones/"+a.name;B&&(C["X-Extole-Jwt"]=B,delete x.jwt);A&&(C.Authorization="Bearer+"+A);H&&(C["X-Extole-Debug"]="true");var I=h.convertToFormUrlEncoded(C,x);h({url:m,type:"POST",headers:C,data:I,complete:function(E,y){var z=/^text\/html(;|$)/;y=y.getResponseHeader("Content-Type");if(/^text\/javascript(;|$)/.test(y))var D=
E;else z.test(y)?(z=document.createElement("div"),z.innerHTML=E,D=t.queryFirst("script",z).innerHTML):c(new g("Received invalid content type: '"+y+"'","invalid_content_type",null,"warn"));if(D)try{(new Function(D))()}catch(F){c(new g("Error in zone script - MESSAGE: "+F.message+" STACK: "+F.stack,"zone_script_error"))}k()},error:function(E,y){try{var z=JSON.parse(this.responseText)}catch(D){z={status:y||null,statusText:E||null}}c(new g(z.message||"Ajax zone request failed",z.code||null,z))},xhrFields:{withCredentials:!0}})}
function c(C){var I=u.merge({originalMessage:C.message,zoneRequestUrl:m||null,zoneDefinition:a},C.data);e(new g("Problem creating zone",C.code||"zone_request_failed",I,C.logLevel||"error"));k()}function k(){"function"===typeof n&&setTimeout(n,500)}e=e||function(){};var m,w=p.deserialize(location.search),x=u.merge({},a.data||a.parameters),B=a.jwt||x.jwt||w.extole_jwt,A=v.get(),G=[l.getProtocol(),l.getProgramDomain()].join(""),H=x.debug&&"false"!==x.debug||extole.IS_DEBUG_ENABLED;extole.isPassRefererInZoneData&&
(x.referer=location.href);extole.CORE_CONFIG.isGlobalZoneParametersEnabled&&(w=r.parseGlobalZoneParameters(w),x=u.merge(x,w));if(extole.createZonePrehandler&&(w=extole.createZonePrehandler(a,x),!1===w)){c(new g("Zone request cancelled","zone_request_cancelled",null,"info"));return}a.element_id&&(x.element_id=a.element_id);(function(){var C=Date.now(),I=C-6E4;f=f.filter(function(E){return E>I});60<f.length?d.warn("Zone request "+a.name+" exceeded maximum number of zone requests per minute: 60"):f.push(C);
a.data=x;x.zone_id=b.create(a,e);x=u.flatten(x);q()})()}});
extole.define("create-zone-executor",["create-zone","ensure-element","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/logger.js","https://origin.xtlo.net/type=core:clientId=1528233037:coreAssetsVersion=175/common/client/token-store.js"],function(r,p,u,t){function l(a,e,n){function q(m){if(m)c(m);else{b=!0;var w=Array.prototype.slice.call(arguments);(e||function(){}).apply(null,w);k()}}function c(m){function w(){setTimeout(function(){v(a,e,n)},1)}n+=1;if(5>n)if(h(m))b=
!1,t.remove(),w();else u[m.logLevel||"error"](m.toString());else u[m.logLevel||"error"](m.toString()),u.warn("ERROR_WOULD_BE_PASSED_TO_CREATE_ZONE_CALLBACK")}var k;d.push(function(m){k=g(m);r(a,q,k);b&&k()})}function v(a,e,n){function q(){var c=!!t.get(),k=!!a.element;!extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled&&!c||extole.isFindElementBeforeZoneRequest&&!k||l(a,e,n)}n=Number(n)||0;t.get()||extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled||f(q);extole.isFindElementBeforeZoneRequest&&
p(a,function(c){a.element=c;q()});q()}function h(a){a=a||{};return a.data&&403===a.data.http_status_code&&("invalid_access_token"===a.code||"expired_access_token"===a.code)}function g(a){var e=!1;return function(){var n=Array.prototype.slice.call(arguments);e||(e=!0,a.apply(null,n))}}var d=new function(){var a=0,e=[],n=this,q=!1;this.push=function(c){e.push(c);this.next()};this.next=function(){function c(){a--;n.next()}if(!q)for(;1>a&&e.length;)e.shift()(c),a++};this.start=function(){q=!1;this.next()};
this.stop=function(){q=!0}},b=!1,f=function(a){function e(){for(;n.length;)n.shift().apply(null,arguments)}var n=[],q=!1;return function(c){n.push(c);q||(q=!0,a(function(){q=!1;e.apply(null,arguments)}))}}(t.fetch);return{initiateExecution:v}});